DB    L ACC01
SYSID L 0
FMT   L MH
LDR   L -----nM2.01200024------h
030   L a|1ucr|||||||
036a  L $$aAT
050   L a|a|||||g|||||
051   L mu||||||
070   L $$aUBG
070a  L $$aVL-WG-UBG
078o  L $$afoo

081b  L $$abar
081d  L $$a2015-06
081i  L $$a$$b$$c$$9
100   L $$aSchag, Helga Elisabeth
331   L $$aDie gotische Apsisverglasung der Kreuzkapelle im Zisterzienserstift Rein
425a  L $$a2015
501   L $$aArbeit an der Bibliothek noch nicht eingelangt - Daten nicht geprüft
504   L $$pfoo$$aspam
519   L $$aGraz, Univ., Masterarb., 2015
655e  L $$uhttp://ema2.uni-graz.at:8090/livelinkdav2/nodes/272307/Schag_Helga%20Elisabeth%2022.06.2015.pdf$$xUBG$$3Volltext
673c  L $$aGraz
750i  L $$atest
752   L $$ager
753i  L $$a
755   L $$aeng
